[package]
name = "d2"
version = "0.1.0"
authors = ["Tw <wei.tan@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
peg = "0.7.0"
